#!/bin/bash

TOP="${HOME}/Documents/Obsidian/Obsidian-Media-Vault/Vinyl"

[ -d "${TOP}" ] || {
  echo "$TOP does not exist or is not a directory. Exiting."
  exit 1
}

cd "${TOP}"

mkartists=
numcols=1
overwrite=
[ "$1" == "-f" ] && overwrite=1

[ "${overwrite}" ] && rm -f ../Artists.md

if [ -f ../Artists.md ]
then
  echo "../Artists.md exists. Use -f option to overwrite. Exiting."
  exit 1
else
  mkartists=1
  echo "# Artists" > ../Artists.md
  echo "" >> ../Artists.md
  echo "## List of Artists in Vault" >> ../Artists.md
  echo "" >> ../Artists.md
  echo "| **Artist Name** | **Artist Name** | **Artist Name** | **Artist Name** | **Artist Name** |" >> ../Artists.md
  echo "|--|--|--|--|--|" >> ../Artists.md
fi

for artist in *
do
  [ "${artist}" == "*" ] && continue
  [ -d "${artist}" ] || continue
  cd "${artist}"
  artistname=
  for album in *.md
  do
    [ "${album}" == "*.md" ] && continue
    [ "${album}" == "${artist}.md" ] && continue
    [ "${artistname}" ] || {
      artistname=`grep "artist:" ${album} | head -1 | \
        awk -F ':' ' { print $2 } ' | sed -e 's/^ *//' -e 's/ *$//'`
    }
    title=`grep "title:" ${album} | awk -F ':' ' { print $2 } ' | \
      sed -e 's/^ *//' -e 's/ *$//' -e "s/^\"//" -e "s/\"$//"`
    echo "- [${title}](${album})" >> /tmp/sa$$
  done
  cd ..
  [ "${mkartists}" ] && {
    [ -f "${artist}/${artist}.md" ] && {
      if [ ${numcols} -gt 4 ]
      then
        printf "| [${artistname}](Vinyl/${artist}/${artist}.md) |\n" >> ../Artists.md
        numcols=1
      else
        printf "| [${artistname}](Vinyl/${artist}/${artist}.md) " >> ../Artists.md
        numcols=$((numcols+1))
      fi
    }
  }
done

[ "${mkartists}" ] && {
  while [ ${numcols} -lt 4 ]
  do
    printf "| " >> ../Artists.md
    numcols=$((numcols+1))
  done
  printf "|\n" >> ../Artists.md
}
