#!/bin/bash
# ![](https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/XXX/YYY.jpg)

TOP="${HOME}/Documents/Obsidian/Obsidian-Media-Vault/Books"

[ -d "${TOP}" ] || {
  echo "$TOP does not exist or is not a directory. Exiting."
  exit 1
}

cd "${TOP}"

rm -f /tmp/notfound
touch /tmp/notfound
rm -f /tmp/missingart
touch /tmp/missingart
for book in */*.md
do
  [ "${book}" == "*/*.md" ] && continue
  [ -f ${book} ] || {
    echo "${book} does not exist. Skipping."
    continue
  }
  grep "/assets/bookcovers/" ${book} > /dev/null || {
    grep "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/" ${book} > /dev/null || {
      echo "${book}: Pattern not found. Skipping." | tee -a /tmp/notfound
      continue
    }
    author=`echo ${book} | awk -F '/' ' { print $1 } '`
    rbook=`echo ${book} | awk -F '/' ' { print $2 } ' | sed -e "s/\.md//"`
    # Replace book cover art link for this book
    if [ -f "../assets/bookcovers/${author}-${rbook}.png" ]
    then
      echo "Inserting cover art link for ${author} - ${rbook}"
      echo "![](../../assets/bookcovers/${author}-${rbook}.png)" > /tmp/__insert__
      echo "" >> /tmp/__insert__
      sed '/## Album Data/e cat /tmp/__insert__' ${book} > /tmp/foo$$
      cp /tmp/foo$$ ${book}
      rm -f /tmp/foo$$ /tmp/__insert__
    else
      echo "Cover art does not exist for ${author} - ${rbook}" | tee -a /tmp/missingart
    fi
  }
done
