#!/bin/bash
#
# get-discogs-artist
#
# Get a Discogs artist profile

# Set to the username of the Discogs collection to query
username="doctorfree"

# URL="https://api.discogs.com/releases"
URL="https://api.discogs.com"
ART="${URL}/artists"

AGE="github.com/doctorfree/MusicPlayerPlus"
UAG="--user-agent \"MusicPlayerPlus/3.0\""
token="CtvkGQluyminrZuarkmuFJZjXFEvUFpNDxkjNnVP"
#artist_id=9462
artist_id=272144
REL="${URL}/artists/${artist_id}/releases?year"

[ -d json ] || mkdir json

# Retrieve artist profile
artist=$(curl --stderr /dev/null \
  -A "${AGE}" "${ART}/${artist_id}" \
  -H "Accept: application/vnd.discogs.v2.plaintext+json" \
  -H "Authorization: Discogs token=${token}" | \
  jq -r '.')

# Retrieve artist releases
releases=$(curl --stderr /dev/null \
  -A "${AGE}" "${REL}" \
  -H "Authorization: Discogs token=${token}" | \
  jq -r '.')

echo "${artist}" > "json/artist_${artist_id}.json"
echo "${releases}" > "json/releases_${artist_id}.json"
