#!/bin/bash
#
# get-discogs-releases
#
# Get your Discogs collection "All" folder items
#
# Valid sort keys are:
# label
# artist
# title
# catno
# format
# rating
# added
# year
#     Parameters
#     username
#         string (required) Example: rodneyfool
#         The username of the collection you are trying to request.
#     folder_id
#         number (required) Example: 3
#         The ID of the folder to request.
#     sort
#         string (optional) Example: artist
#         Sort items by this field (see below for all valid sort keys.
#     sort_order
#         string (optional) Example: desc
#         Sort items in a particular order (asc or desc)

# Set to the username of the Discogs collection to query
username="doctorfree"

# URL="https://api.discogs.com/releases"
URL="https://api.discogs.com"
USR="${URL}/users/${username}"
FDR="${URL}/users/${username}/collection/folders"

AGE="github.com/doctorfree/MusicPlayerPlus"
token="CtvkGQluyminrZuarkmuFJZjXFEvUFpNDxkjNnVP"

[ -d json ] || mkdir json

# Retrieve collection folder
releases=$(curl --stderr /dev/null \
  -A "${AGE}" "${FDR}/0/releases?page=20" \
  -H "Authorization: Discogs token=${token}" | \
  jq -r '.')

echo "${releases}" > "json/doctorfree_releases_20.json"
